// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthMateRepository.Models;

public partial class ArticleLike
{
    public int LikeId { get; set; }

    public int UserId { get; set; }

    public int ArticleId { get; set; }

    public DateTime LikedAt { get; set; }

    public virtual Article Article { get; set; }

    public virtual User User { get; set; }
}