// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthMateRepository.Models;

public partial class Collection
{
    public int CollectionId { get; set; }

    public string Name { get; set; }

    public string ImageUrl { get; set; }

    public virtual ICollection<Recipe> Recipes { get; set; } = new List<Recipe>();
}