// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthMateRepository.Models;

public partial class DailyLog
{
    public int DailyLogId { get; set; }

    public int UserId { get; set; }

    public DateOnly LogDate { get; set; }

    public decimal Calories { get; set; }

    public decimal Protein { get; set; }

    public decimal Fat { get; set; }

    public decimal Carbs { get; set; }

    public decimal Fiber { get; set; }

    public virtual ICollection<Meal> Meals { get; set; } = new List<Meal>();

    public virtual User User { get; set; }
}