// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthMateRepository.Models;

public partial class MealItem
{
    public int MealItemId { get; set; }

    public int MealId { get; set; }

    public string FoodName { get; set; }

    public decimal Quantity { get; set; }

    public string Unit { get; set; }

    public decimal Calories { get; set; }

    public decimal Protein { get; set; }

    public decimal Fat { get; set; }

    public decimal Carbs { get; set; }

    public decimal Fiber { get; set; }

    public virtual Meal Meal { get; set; }
}