// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthMateRepository.Models;

public partial class Meal
{
    public int MealId { get; set; }

    public int DailyLogId { get; set; }

    public string MealType { get; set; }

    public virtual DailyLog DailyLog { get; set; }

    public virtual ICollection<MealItem> MealItems { get; set; } = new List<MealItem>();
}