// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthMateRepository.Models;

public partial class RecipeLike
{
    public int LikeId { get; set; }

    public int UserId { get; set; }

    public int RecipeId { get; set; }

    public DateTime LikedAt { get; set; }

    public virtual Recipe Recipe { get; set; }

    public virtual User User { get; set; }
}