// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthMateRepository.Models;

public partial class Transaction
{
    public int TransactionId { get; set; }

    public int UserId { get; set; }

    public int PackageId { get; set; }

    public int PaymentMethodId { get; set; }

    public string TransactionCode { get; set; }

    public decimal Amount { get; set; }

    public string Status { get; set; }

    public DateTime PurchasedAt { get; set; }

    public virtual PremiumPackage Package { get; set; }

    public virtual PaymentMethod PaymentMethod { get; set; }

    public virtual User User { get; set; }
}